/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as GuestLoginRouteImport } from './app/routes/guest-login'
import { Route as ChatRouteImport } from './app/routes/chat'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ChatIndexRouteImport } from './app/routes/chat.index'
import { Route as MapProjectIdRouteImport } from './app/routes/map.$projectId'
import { Route as ChatChatIdRouteImport } from './app/routes/chat.$chatId'

const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/guest-login',
  path: '/guest-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const MapProjectIdRoute = MapProjectIdRouteImport.update({
  id: '/map/$projectId',
  path: '/map/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/guest-login': typeof GuestLoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/map/$projectId': typeof MapProjectIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest-login': typeof GuestLoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/map/$projectId': typeof MapProjectIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/guest-login': typeof GuestLoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/map/$projectId': typeof MapProjectIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/guest-login'
    | '/chat/$chatId'
    | '/map/$projectId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guest-login' | '/chat/$chatId' | '/map/$projectId' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/guest-login'
    | '/chat/$chatId'
    | '/map/$projectId'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  GuestLoginRoute: typeof GuestLoginRoute
  MapProjectIdRoute: typeof MapProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guest-login': {
      id: '/guest-login'
      path: '/guest-login'
      fullPath: '/guest-login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/map/$projectId': {
      id: '/map/$projectId'
      path: '/map/$projectId'
      fullPath: '/map/$projectId'
      preLoaderRoute: typeof MapProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  GuestLoginRoute: GuestLoginRoute,
  MapProjectIdRoute: MapProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
